spring:
  datasource:
    # Deve manter a mesam URL no H2 no console => JDBC URL: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true # Adicione isso para evitar bloqueios de conex√£o
